default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] || 'localhost'%>
  port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] || 3306 %>
  username: <%= ENV['MYSQL_ENV_MYSQL_ROOT_USER'] || 'root' %>
  password: <%= ENV['MYSQL_ENV_MYSQL_ROOT_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE_DEV'] || 'camaleon_dev'

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE_TEST'] || 'camaleon_test'

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE_DEV'] || 'camaleon_production'

